### ISSUE TITLE
No custom span tag for APM traces

### ISSUE THREAD

**Issue by davenewza** [DataDog/dd-trace-dotnet#1993]
**Describe the bug**
I am trying to add custom tags to our APM span traces using the .NET Core `Datadog.Trace` package.  However, these tags do not appear in the traces on Datadog.

**To Reproduce**
The following code exists on the controller:

```
var scope = Tracer.Instance.ActiveScope;
scope.Span.SetTag("tenantId", tenantId);
scope.Span.SetTag("instanceName", Environment.MachineName);
```
I can confirm that:
 - `Tracer.Instance.ActiveScope` is not null and is type `Datadog.Trace.Scope`
 -  that the `Datadog.Trace` package is correctly attached to the tracer (see my fix here https://github.com/DataDog/dd-trace-dotnet/issues/1986).
 -  that `tenantId` and `Environment.MachineName` are not null or empty.

Example trace tags in Datadog shows that `tenantId` and `instanceName` don't exist:
![image](https://user-images.githubusercontent.com/6212830/140487131-64e38666-3146-4fe3-b7b6-2d386a53a54a.png)

**Expected behavior**
`tenantId` and `instanceName` should be root level fields in the span trace tag JSON structure above.

**Runtime environment (please complete the following information):**
- Datadog container agent (Kubernetes): `gcr.io/datadoghq/agent:latest`
- `Datadog.Trace` and debian tracer installer: 1.29
- Docker linux base `mcr.microsoft.com/dotnet/aspnet:5.0`
- .NET 5.0

**Comment by davenewza** [comment]
I've attempted to troubleshoot further with docker-compose on my local with no luck.  APM logs are pushing through just fine (so we know this is definitely working) but my custom tags aren't representing in Datadog.

```
  myapplication.api:
    image: myapplication.api
    build:
      context: .
      dockerfile: src/server/myapplication.program/dockerfile
      target: runner
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: dockerlocal
      DD_AGENT_HOST: "datadog-agent"
      DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED: "true"
      DD_RUNTIME_METRICS_ENABLED: "true"

  datadog-agent:
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      DD_APM_ENABLED: "true"
      DD_SITE: "datadoghq.eu"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_DOGSTATSD_PORT: 8125
      DD_API_KEY: "xyz"
```
