### ISSUE TITLE
Container image dd-lib-dotnet-init:v2.33.0 missing

### ISSUE THREAD

**Issue by dotTrench** [DataDog/dd-trace-dotnet#4367]
**Describe the bug**
Using auto instrumentation in kubernetes with the datadog admission controller, it seems like the container image for `dd-lib-dotnet-init:v2.33.0` can not be pulled causing a 'ImagePullBackOff' error in the init container.

Looking at the public repositories it seems like the tag `v2.33.0` has not been pushed.

https://gcr.io/datadoghq/dd-lib-dotnet-init
https://gallery.ecr.aws/datadog/dd-lib-dotnet-init
https://hub.docker.com/r/datadog/dd-lib-dotnet-init/tags

**To Reproduce**
1. Enable admission controller on the datadog kubernetes agent.
2. Apply the following labels and annotations on a deployment.
```yaml
...
template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
        ...
      annotations:
        admission.datadoghq.com/dotnet-lib.version: v2.33.0
```

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic via kubernetes admission controller
- Tracer version: v2.33.0
- OS: Kubernetes v1.26.3
- CLR: .NET 7.0

**Additional context**
We're currently running v2.32.0 via this method without any issues.

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>
