### ISSUE TITLE
Request for Windows/amd64 Support for Datadog .NET trace Library docker image

### ISSUE THREAD

**Issue by LQss11** [DataDog/dd-trace-dotnet#5946]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**  
- **Framework or library name:** Datadog .NET trace Library  
- **Library type:** Automatic instrumentation library  
- **Library version:** Latest  

**Is your feature request related to a problem? Please describe.**  
The Datadog .NET trace Library functions correctly on Linux nodes but fails on Windows nodes within my AKS cluster. The infrastructure is Windows/amd64, and there is no current support for this architecture with the library.

**Describe the solution you'd like**  
Please add support for the Windows/amd64 architecture to enable the .NET trace Library on  [docker.io/datadog/dd-lib-dotnet-init:latest](https://hub.docker.com/layers/datadog/dd-lib-dotnet-init/latest/images/sha256-31e0aaef95f79ef2e2f41ed172792046bd1b08a411de7632d5471f912539d638?context=explore) to work on Windows nodes in Kubernetes.

**Describe alternatives you've considered**  
Running applications on Linux nodes was considered but is not viable due to scheduling constraints and workload requirements.

**Additional context**  
The issue persists despite correct configuration of the Datadog Helm chart and annotations. Here is the relevant manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-app
  template:
    metadata:
      labels:
        app: windows-app
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: "latest"
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: windows-container
          resources: {}
          image: <MyWindowsImage>
```
