### ISSUE TITLE
How do I add custom tags to trace metrics?

### ISSUE THREAD

**Issue by neufeldtech** [DataDog/dd-trace-dotnet#820]
I'm attempting to add custom tags to .net core metrics such as `trace.aspnet_core.request.hits` but have been unsuccessful so far.

**To Reproduce**

Platform: Kubernetes
Instrumentation Type: Automatic via agent sidecar container
Version: Using dotnet-agent v1.15.0
Env var snippet:
```yaml
....
- env:
        - name: DD_TAGS
          value: role:frontend
        - name: COMPlus_PerfMapEnabled
          value: "1"
        - name: CORECLR_ENABLE_PROFILING
          value: "1"
        - name: CORECLR_PROFILER
          value: '{846F5F1C-F9AE-4B07-969E-05C26BC060D8}'
        - name: CORECLR_PROFILER_PATH
          value: /opt/datadog/Datadog.Trace.ClrProfiler.Native.so
        - name: DD_INTEGRATIONS
          value: /opt/datadog/integrations.json
        - name: DD_DOTNET_TRACER_HOME
          value: /opt/datadog
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DATADOG__LOGGING__ENABLED
          value: "true"
.....
```

**Expected behavior**
I expect to be able to query and graph in Datadog via facets like:

```
sum:trace.aspnet_core.request.hits{env:stg} by {service,role}.as_count()
```

**Actual Behaviour**
The `role` tag is not assigned to this metric, so I cannot aggregate on it.
```
sum:trace.aspnet_core.request.hits{env:stg} by {service}.as_count()
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8252744/88566405-90205380-cffb-11ea-8afb-9b6c362cf4d9.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic (Kubernetes sidecar container)
- Tracer version: 1.15.0
- OS: Linux
- CLR: 2.2.8

**Additional context**
With node.js pods, I'm able to set `DD_TAGS=role:foobar` and have this tag show up on node.js metrics such as 
`sum:runtime.node.event_loop.delay.sum{env:stg} by {service,role}.as_count()`. Given this experience, I expect that my DD-agent daemonset is set up correctly to be able to support this, since it's doing it properly with node.js.
